### ISSUE TITLE
Geolocation error

### ISSUE THREAD

**Issue by nick773312** [HighMileage/knowyourbeat#3]
hey im trying to add it to my own site but i get the geo problem Geolocation error: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)..

**Comment by HighMileage** [comment]
@ncamacho97 were you able to figure this out? Basically you need to make sure that you're serving the page over https. Let's encrypt is a pretty easy solution if you don't want to have to pay for a cert.
